### PR TITLE
Add feature flag to enable sensor 2.8 Volt mode

### LINKED ISSUE #1: Enable 2.8V mode
Hi, thanks for writing and open-sourcing this binding!

Is there a way to activate the 2.8V mode for the Vl53l1x? It seems that by default the sensor operates in 1.8V mode and has to be switched by compiling the ST-drivers with the `USE_I2C_2V8` preprocessor macro defined (see [driver user manual](https://www.st.com/content/ccc/resource/technical/document/user_manual/group0/98/0d/38/38/5d/84/49/1f/DM00474730/files/DM00474730.pdf/jcr:content/translations/en.DM00474730.pdf) section 2.5.9, although it says `USE_I2C_2V8k` there which seems to be wrong...).

This is also done e.g. in the [Pololu implementation](https://github.com/pololu/vl53l1x-st-api-arduino/blob/master/vl53l1x-st-api/vl53l1_api.c#L757) and probably makes sense as a default since most existing breakout boards assume that the sensor is used with 2.8 Volts.

Maybe this could be done using a Cargo feature and then passed on in `build.rs` to the Makefile?

Thanks!
Michael

### PR DESCRIPTION
**Pull request by michael-p**
Closes #1

### CODE REVIEW

**Comment by michael-p** [comment]
Rebased to fix merge conflicts.

**Comment by braincore** [comment]
Thanks again!

1. Did you ever get to the bottom of why this flag appears unnecessary?
2. Do you want any additional attribution (i.e. contributors)?
3. Would you like write access to this repo so you can make changes directly in the future?

**Comment by michael-p** [comment]
Thanks for merging!

No I don't know what the flag actually does, the only difference in ST's driver is that it sets an additional I2C register on startup but since ST doesn't provide register maps I have no idea what a difference that makes. My hope is that you magically get better measurements :)

Attribution is not necessary, these were just minor things. Concerning write access: I think this crate is already pretty much "done" in terms of functionality, so I'll probably only have some more small bug fixes in the future, if at all. So write-access seems overkill, but thanks!

PS: Do you mind releasing a new version to crates.io? :) Thanks again for your work in this crate!

**Comment by braincore** [comment]
Done! New version is v1.2.0.

**Pull request merged**
